name: pyinstaller

on:
  push:
    branches: [ master ]

jobs:

  job_1:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        pyside2-rcc resources.qrc -o rc_ressources.py
        python -m PyInstaller main.py --onefile --noconsole --name="LapsAnalyzer" --icon=assets/images/icon.ico
    - name: Linux artefact
      uses: actions/upload-artifact@v1
      with:
        name: LapsAnalyzer_linux
        path: ./dist/LapsAnalyzer
            
  job_2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        pyside2-rcc resources.qrc -o rc_ressources.py
        pyinstaller main.py --onefile --noconsole --name="LapsAnalyzer" --icon=assets/images/icon.ico
    - name: Mac artefact
      uses: actions/upload-artifact@v1
      with:
        name: LapsAnalyzer_mac
        path: ./dist/LapsAnalyzer
        
  job_3:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        pyside2-rcc resources.qrc -o rc_ressources.py
        pyinstaller main.py --onefile --noconsole --name="LapsAnalyzer" --icon=assets/images/icon.ico
    - name: Windows artefact
      uses: actions/upload-artifact@v1
      with:
        name: LapsAnalyzer_win
        path: ./dist/LapsAnalyzer.exe
